name: Test
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - main
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python x64
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - name: Set up Python x86
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x86"
    - name: output python x86 version
      run: C:\hostedtoolcache\windows\Python\3.10.0\x86\python.exe --version
    - name: output python x64 version
      run: C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe --version
    - name: create venv
      run: |
        C:\hostedtoolcache\windows\Python\3.10.0\x86\python.exe  -m venv venv32
        C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe  -m venv venv
    - name: run build.ps1
      run: ./build.ps1
